apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: flask-app-split
spec:
  service: flask-app
  backends:
    - service: flask-app-primary
      weight: 80
    - service: flask-app-canary
      weight: 20
