apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
      version: canary
  template:
    metadata:
      labels:
        app: flask-app
        version: canary
    spec:                        
      containers:
      - name: flask
        image: sukanya996/bule-green:blue-1
        ports:
        - containerPort: 5000
